### ISSUE TITLE
bugfix: JOB_NAMESPACE变量无法使用，值为空

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#1222]
**Version / Branch / tag**
3.6.x

**出了什么问题？(What Happened?)**
使用JOB_NAMESPACE_{var_name}魔法变量，没有值。脚本如下：
```
# job_import {{JOB_NAMESPACE_log_dir}}
echo ${JOB_NAMESPACE_log_dir} 
```
**如何复现？(How to reproduce?)**
见问题描述

**预期结果(What you expect?)**
正确输出命名空间变量的值

**Comment by wangyu096** [comment]
问题原因：
上一步骤输出的变量值不包含ip，导致当前步骤解析变量值的时候出现异常。
```
2022-08-24 16:02:03.623]  WARN [,c42318c5bc50b068,9b4ca41363362818] 29745 --- [gse.task.service.job.execute-22] c.t.bk.job.common.util.json.JsonMapper   : Write to json string error:{null=stage-bk-3}

com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.HashMap["null"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:288)
        at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1337)
        at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1231)
        at com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:709)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:681)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4409)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3663)
        at com.tencent.bk.job.common.util.json.JsonMapper.toJson(JsonMapper.java:80)
        at com.tencent.bk.job.common.util.json.JsonUtils.toJson(JsonUtils.java:125)
        at com.tencent.bk.job.execute.engine.variable.JobNamespaceVariableResolver.resolve(JobNamespaceVariableResolver.java:86)
        at com.tencent.bk.job.execute.engine.variable.JobBuildInVariableResolver.resolve(JobBuildInVariableResolver.java:60)
        at com.tencent.bk.job.execute.engine.executor.ScriptGseTaskStartCommand.appendImportVariablesDeclareScript(ScriptGseTaskStartCommand.java:401)
        at com.tencent.bk.job.execute.engine.executor.ScriptGseTaskStartCommand.buildChangeableVarDeclareScript(ScriptGseTaskStartCommand.java:514)
        at com.tencent.bk.job.execute.engine.executor.ScriptGseTaskStartCommand.buildRequestWithChangeableParam(ScriptGseTaskStartCommand.java:464)
        at com.tencent.bk.job.execute.engine.executor.ScriptGseTaskStartCommand.buildShellScriptRequestForPlan(ScriptGseTaskStartCommand.java:246)
        at com.tencent.bk.job.execute.engine.executor.ScriptGseTaskStartCommand.buildShellScriptRequest(ScriptGseTaskStartCommand.java:219)
```
