### ISSUE TITLE
bugfix: 打开历史作业的执行详情页面，报"内部服务器异常"

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#1229]
**Version / Branch / tag**

3.6.0

**出了什么问题？(What Happened?)**

打开历史作业的执行详情页面，报"内部服务器异常"

**如何复现？(How to reproduce?)**

复现条件：3.6.0版本升级之前的作业打开有问题

**预期结果(What you expect?)**

打开历史作业的执行详情页面，没有报错且显示正常

**Comment by wangyu096** [comment]
- 报错
```
[2022-08-29 12:25:42.139] ERROR [job-execute,82395772497191ade38f869c6e3ffb84,f3211c9273e220e3] 1052 --- [http-nio-10502-exec-195] b.j.c.w.e.h.WebExceptionControllerAdvice : Handle Exception, uri: /web/execution/scope/biz/1045/step-execution-result/log-content/2549000000/0/0:127.0.0.1

java.lang.NullPointerException: null
        at com.tencent.bk.job.execute.service.impl.ScriptAgentTaskServiceImpl.getAgentTaskByHost(ScriptAgentTaskServiceImpl.java:100)
        at com.tencent.bk.job.execute.service.impl.LogServiceImpl.getScriptHostLogContent(LogServiceImpl.java:148)
        at com.tencent.bk.job.execute.api.web.impl.WebTaskExecutionResultResourceImpl.getScriptLogContentByIp(WebTaskExecutionResultResourceImpl.java:615)
```

- 缺陷原因
```
    @Override
    public AgentTaskDTO getAgentTaskByHost(StepInstanceBaseDTO stepInstance,
                                           Integer executeCount,
                                           Integer batch,
                                           HostDTO host) {
        AgentTaskDTO agentTask = null;
        Long hostId = host.getHostId();
        if (hostId != null) {
            // 根据hostId查询
            agentTask = scriptAgentTaskDAO.getAgentTaskByHostId(stepInstance.getId(), executeCount, batch, hostId);
        } else if (StringUtils.isNotEmpty(host.toCloudIp())) {
            // 根据ip查询的模式，有两种情况，数据可能在gse_script_agent_task/gse_task_ip_log表中，优先查询gse_script_agent_task
            HostDTO queryHost = getStepHostByIp(stepInstance, host.toCloudIp());
            if (queryHost != null) {
                agentTask = scriptAgentTaskDAO.getAgentTaskByHostId(stepInstance.getId(), executeCount, batch,
                    queryHost.getHostId());
            } else {
                // 根据ip查询gse_task_ip_log表中的数据
                agentTask = gseTaskIpLogDAO.getAgentTaskByIp(stepInstance.getId(), executeCount, host.toCloudIp());
            }
        }
        return agentTask;
    }
```

queryHost.getHostId可能为null
