### ISSUE TITLE
bugfix: 通过batch_get_job_instance_ip_log,报"系统内部异常"

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#1242]
**Version / Branch / tag**

3.6.0-rc.28

**出了什么问题？(What Happened?)**

- 现象

通过batch_get_job_instance_ip_log,报"系统内部异常"。

- 报错内容

```
[2022-08-31 11:35:03.397] ERROR [job-execute,3fd9a146a8050c232aa6e47b853190b6,72f3ce049bc9c6f8] 18252 --- [http-nio-10502-exec-130] b.j.c.w.e.h.EsbExceptionControllerAdvice : Handle exception

java.lang.IllegalArgumentException: Invalid cloudIp : 127.0.0.1
	at com.tencent.bk.job.common.model.dto.HostDTO.fromCloudIp(HostDTO.java:127)
	at com.tencent.bk.job.execute.api.esb.v3.EsbBatchGetJobInstanceIpLogV3ResourceImpl.lambda$buildFileLogs$3(EsbBatchGetJobInstanceIpLogV3ResourceImpl.java:212)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.tencent.bk.job.execute.api.esb.v3.EsbBatchGetJobInstanceIpLogV3ResourceImpl.buildFileLogs(EsbBatchGetJobInstanceIpLogV3ResourceImpl.java:220)
	at com.tencent.bk.job.execute.api.esb.v3.EsbBatchGetJobInstanceIpLogV3ResourceImpl.batchGetJobInstanceIpLogs(EsbBatchGetJobInstanceIpLogV3ResourceImpl.java:112)
	at com.tencent.bk.job.execute.api.esb.v3.EsbBatchGetJobInstanceIpLogV3ResourceImpl$$FastClassBySpringCGLIB$$39200b9c.invoke(<generated>)
```

- 其他
<img width="513" alt="image" src="https://user-images.githubusercontent.com/28581184/187647134-69381372-8457-4cdd-b3f9-387a4420c292.png">

**如何复现？(How to reproduce?)**
- 复现条件
1. 文件分发任务
2. 目标下载异常

**预期结果(What you expect?)**

API不报错

**Comment by wangyu096** [comment]
原因:
文件任务结果处理，当走到处理失败目标agent任务的分支的时候，mongodb中存储的执行日志内容，没有使用正确的ip(云区域+IP)
