### ISSUE TITLE
bugfix: 运营分析页面，获取累计任务执行次数API 错误

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#423]
现象：
![image](https://user-images.githubusercontent.com/28581184/141746835-53f0db9f-7566-46fc-8889-9cba2989b460.png)
后台日志：
`
[2021-11-15 15:04:20.070][b2052d416048ea45|4f96cf90cd798b73][http-nio-10510-exec-7] WARN  c.t.b.j.c.w.e.h.WebExceptionControllerAdvice:handleControllerException:105 - Handle exception
java.lang.NumberFormatException: For input string: "2152967999"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.tencent.bk.job.analysis.service.CommonStatisticService.getTrendByMetric(CommonStatisticService.java:167)
	at com.tencent.bk.job.analysis.api.web.impl.WebStatisticsResourceImpl.trends(WebStatisticsResourceImpl.java:125)
`

**Comment by wangyu096** [comment]
程序中使用Integer存储该值，导致溢出
