### ISSUE TITLE
bugfix: 高危脚本检查后台报错

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#560]
**版本/分支/tag**
3.4.3
**问题描述**
执行高危脚本检查的时候，后台报错
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 39
        at com.tencent.bk.job.manage.manager.script.check.checker.DefaultChecker.checkScriptLines(DefaultChecker.java:65)
        at com.tencent.bk.job.manage.manager.script.check.checker.DefaultChecker.checkScriptLines(DefaultChecker.java:52)
        at com.tencent.bk.job.manage.manager.script.check.checker.ScriptLogicChecker.call(ScriptLogicChecker.java:70)
        at com.tencent.bk.job.manage.manager.script.check.checker.ScriptLogicChecker.call(ScriptLogicChecker.java:44)
```
**如何复现**
当脚本内容最后一行为#开头的时候。比如：
```
#!/bin/bash

anynowtime="date +'%Y-%m-%d %H:%M:%S'"
NOW="echo [\`$anynowtime\`][PID:$$]"

##### 可在脚本开始运行时调用，打印当时的时间戳及PID。
function job_start
{
    echo "`eval $NOW` job_start"
}

##### 可在脚本执行成功的逻辑分支处调用，打印当时的时间戳及PID。
function job_success
{
    MSG="$*"
    echo "`eval $NOW` job_success:[$MSG]"
    exit 0
}

##### 可在脚本执行失败的逻辑分支处调用，打印当时的时间戳及PID。
function job_fail
{
    MSG="$*"
    echo "`eval $NOW` job_fail:[$MSG]"
    exit 1
}

job_start

###### 作业平台中执行脚本成功和失败的标准只取决于脚本最后一条执行语句的返回值
###### 如果返回值为0，则认为此脚本执行成功，如果非0，则认为脚本执行失败
###### 可在此处开始编写您的脚本逻辑代码
```
**预期结果**
后台不报错

**Comment by wangyu096** [comment]
错误原因： 解析脚本的代码不正确，导致数组越界

**Comment by wangyu096** [comment]
3.4.4 版本修复
