### ISSUE TITLE
bugfix: 作业脚本使用job_import方式导入变量，如果该作业未定义变量，作业状态为“状态异常”

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#581]
**版本/分支/tag**
3.4.3
**问题描述**
1. 创建作业，不包含任何变量
2. 脚本内容中使用job_import 导入变量功能
```
#!/bin/bash

# job_import {{JOB_LAST_ALL}}
# job_import {{JOB_LAST_SUCCESS}}
# job_import {{JOB_LAST_FAIL}}

echo ${JOB_LAST_ALL}
echo ${JOB_LAST_SUCCESS}
echo ${JOB_LAST_FAIL}

echo "hello"
```
3. 结果：
后台报错
```
[2021-12-30 16:08:53.826] ERROR [,a0ffe12c673c2435,cb1e18fcf4b1dba6] 3384 --- [gse.task.service.job.execute-3603] c.t.b.j.e.e.listener.GseStepListener     : Handling gse step control message error,stepInstanceId:22761329800

java.lang.NullPointerException: null
	at com.tencent.bk.job.execute.engine.executor.ScriptTaskExecutor.buildConstVarDeclareScript(ScriptTaskExecutor.java:278)
	at com.tencent.bk.job.execute.engine.executor.ScriptTaskExecutor.buildRequestWithConstParamOnly(ScriptTaskExecutor.java:254)
	at com.tencent.bk.job.execute.engine.executor.ScriptTaskExecutor.buildShellScriptRequest(ScriptTaskExecutor.java:177)
	at com.tencent.bk.job.execute.engine.executor.ScriptTaskExecutor.getScriptRequest(ScriptTaskExecutor.java:134)
	at com.tencent.bk.job.execute.engine.executor.ScriptTaskExecutor.startGseTask(ScriptTaskExecutor.java:128)
	at com.tencent.bk.job.execute.engine.executor.AbstractGseTaskExecutor.execute(AbstractGseTaskExecutor.java:333)
	at com.tencent.bk.job.execute.engine.GseTaskManager.executeTask(GseTaskManager.java:534)
	at com.tencent.bk.job.execute.engine.GseTaskManager.startStep(GseTaskManager.java:242)
	at com.tencent.bk.job.execute.engine.listener.GseStepListener.handleMessage(GseStepListener.java:77)
```

作业状态显示“状态异常”
**如何复现**
见问题描述
**预期结果**
JOB_LAST_ALL、JOB_LAST_SUCCESS、JOB_LAST_FAIL 变量正确import

**Comment by wangyu096** [comment]
- 定位结果
```
 private api_script_request buildShellScriptRequest(StepInstanceDTO stepInstance) {
        api_script_request request;
        boolean containsAnyImportedVariable = false;
        List<String> importVariables = null;
        if (shouldParseBuildInVariables(stepInstance)) {
            importVariables = VariableResolver.resolveJobImportVariables(stepInstance.getScriptContent());
            if (CollectionUtils.isNotEmpty(importVariables)) {
                log.info("Parse imported variables, stepInstanceId:{}, variables: {}", stepInstance.getId(),
                    importVariables);
                containsAnyImportedVariable = true;
            }
        }
        if (!containsAnyImportedVariable && !taskVariablesAnalyzeResult.isExistAnyVar()) {
            request = buildRequestWithoutAnyParam(stepInstance);
        } else if (taskVariablesAnalyzeResult.isExistOnlyConstVar()) {
            request = buildRequestWithConstParamOnly(stepInstance, taskVariablesAnalyzeResult.getTaskVars(),
                importVariables);
        } else {
            request = buildRequestWithChangeableParam(stepInstance, taskVariablesAnalyzeResult, importVariables);
        }
        return request;
    }
```
这段代码构造请求的判断条件有问题
